@startuml
'https://plantuml.com/sequence-diagram

autonumber

box AviaSchedule
boundary Handler
control Controller
control ImportFlightUseCase
control Saver
database Repository as db
end box
participant ЯндексAPI as ya

Handler -> Controller: Надо импортировать расписание
Controller -> ImportFlightUseCase: Импортируй расписание
ImportFlightUseCase -> ya: Дай расписание
ya --> ImportFlightUseCase: Расписание
ImportFlightUseCase -> ImportFlightUseCase: Обработка данных
ImportFlightUseCase -> Saver: Сохрани данные
Saver -> db: Сохранить

@enduml